### ISSUE TITLE
Error when trying to add an element if there is no scene or image

### ISSUE THREAD

**Issue by kuhlkrein** [GazePlay/VisualSceneDisplay#5]
![image](https://user-images.githubusercontent.com/24478346/80611345-c40acd80-8a3a-11ea-9298-2a6fa16f5e72.png)

first console error:
null pointer error when trying to get length on '**Add**' button click

second console error:
ctx.dialogRef.close is not a function  when trying to close on '**Cancel**' button click

**Comment by kuhlkrein** [comment]
@TelmoMS it seems that there are some errors when there is no scene or image.

**Comment by TelmoMS** [comment]
I fixed the property 'length' or null error, the second error only happens when I have "providers: [ { provide : MatDialogRef, useValue: {}}]" in @Component, I am not really sure how to fix it.
